config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes, :categories

  root to:'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :notes, dependent: :destroy
  has_many :categories, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # To facilitate signing up with a user_name or email
  before_action :configure_permitted_parameters, if: :devise_controller?
  # ----------

  def after_sign_in_path_for(resource)
    notes_path
  end

  # To facilitate signing up with a user_name or email
  protected

  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
  #-----------
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.where(user_id: current_user.id).order("name")
  end

  def show
    @notes = @category.notes #because of the associations in the model files we can call all notes in any specific category in this way.
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
      flash[:alert] = 'Your new category has been successfully created.'
      redirect_to :action => 'index'
    else
      flash.now[:alert] = 'Error creating the new category, please try again!'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:alert] = "Your updated category has been saved."
      redirect_to category_path
    else
      flash.now[:alert] = "Couldn't update your category, please try again or cancel!"
      render 'edit'
    end
  end

  def destroy
    if @category.destroy
      flash[:alert] = "Your category has been deleted successfully"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "We couldn't delete your category, please try again!"
      render 'show'
    end
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notes = Note.where(user_id: current_user.id).order("updated_at DESC")
  end

  def show
    @category = Category.find(@note[:category_id])
  end

  def new
    @note = current_user.notes.build
    @categories = Category.where(user_id: current_user.id)
  end

  def create
    @note = current_user.notes.build(note_params)
    @note.user_id = current_user.id
    if @note.save
      flash[:alert] = "Your note has been saved"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "Error saving your new note, please try again!"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update_attributes(note_params)
      flash[:alert] = "Your updated note has been saved."
      redirect_to note_path
    else
      flash.now[:alert] = "Couldn't update your note, please try again or cancel!"
      render 'edit'
    end
  end

  def destroy
    if @note.destroy
      flash[:alert] = "Your note has been deleted successfully"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "We couldn't delete your note, please try again!"
      render 'show'
    end
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body, :category_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |category| %>
  <p>
    <%= category.label :name %><br />
    <%= category.text_field :name %><br />
  </p>
  <p>
    <%= category.label :description %><br />
    <%= category.text_area :description, cols: "50", rows: "6" %><br />
  </p>
  <p>
    <%= category.submit 'Save category' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit your category</h1>
<hr />
<%= render 'categories/form' %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/categories/index.html.erb
<div class="catigisLisDiv" style="text-align: center;">
  <h1 style="margin: 0 auto;">Your catigories list:</h1>
</div>
<p><%= link_to "View available notes", notes_path %></p>
<hr />
<ol>
<% @categories.each do |category| %>
  <% if category.user_id === current_user.id %>
    <li><%= link_to category[:name], category %><small> (Updated on: <%= category[:updated_at].strftime("%b %d. %Y") %> - Contains <%= category.notes.count %> <%= category.notes.count > 1 || category.notes.count < 1 ? 'notes' : 'note'%>)</small></li>
  <% end %>
<% end %>

app/views/categories/new.html.erb
<h1>Add a new category</h1>
<hr />
<%= render 'categories/form' %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/categories/show.html.erb
<% if @category.user_id == current_user.id %>
  <h3><%= @category[:name] %></h3>
  <small>
    <%= @category[:created_at].strftime("%b %d. %Y - %H:%M:%S") %>
    <% if @category[:created_at] != @category[:updated_at] %>
      <small> - updated on: <%= @category[:updated_at].strftime("%b %d. %Y - %H:%M:%S") %></small>
    <% end %>
  </small>
  <hr>
  <table>
    <td><h3>Description:</h3></td>
    <td><p><%= @category[:description] %></p></td>
  </table>
  <ol>
  <% if @notes.each do |note| %>
    <li><%= link_to note.title, note_path(:id => note.id) %></li>
  <% end.empty? %>
    <p>Sorry, no notes are available in this category!</p>
  <% end %>
  </ol>
  <hr />
  <small> <%= link_to 'Edit category', action: 'edit' %> - <%= link_to 'Delete category and all its notes', @category, :method => :delete, data: { confirm: "Are you sure you want to delete this category with all its notes?\n\nOnce done you can\'t revoke this action!" } %> - <%= link_to 'Categories', action: 'index' %> - <%= link_to 'Notes', notes_path %></small>
<% else %>
  <h3>Please follow one of the below links:</h3>
  <p><%= link_to 'Categories', action: 'index' %> - <%= link_to 'Notes', notes_path %></p>
<% end %>

app/views/home/index.html.erb
<h1> Welcome to My-Notes </h1>
<hr>
<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Log in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| -%>
  <script>alert('<%= msg %>')</script>
<% end -%>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
    .body {
      background-size: cover;
      background-repeat: no-repeat;
      background-image: url(/assets/bg01.jpg);
      background-attachment: fixed;
    }

     #navigation{
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 9999;
    }
    </style>
    <link rel="stylesheet" href="https://bootswatch.com/4/cerulean/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <title>My Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="body">
    <nav id="navigation" class="navbar navbar-expand-lg navbar-dark bg-primary">

      <a class="navbar-brand" style="color: white;">
        <% if current_user %>
          <nav class="navLeft" style="width: 75%; color: white;">
            <%= current_user.user_name %>'s Notes - <small><%= link_to "Create new note", new_note_path, style:"color:white;" %></small> - <small><%= link_to "Create new category", new_category_path, style:"color:white;" %></small>
          </nav>
          <nav class="navRight" style="width: 25%; text-align: right;">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, style:"color:white;" %>
          </nav>
        <% end %>
      </a>
    </nav>
    <%= render 'layouts/alerts' %>
    <nav class="contentNav" style="width: 600px; background: white; margin: 0 auto; padding: 10px; border-radius: 30px;">
      <%= yield %>
    </nav>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |note| %>
  <p>
    <%= note.label :title %><br />
    <%= note.text_field :title %><br />
  </p>
  <p>
    <%= note.label :body %><br />
    <%= note.text_area :body, cols: "50", rows: "6" %><br />
  </p>
  <p>
    <%= note.select :category_id, Category.where(user_id: current_user.id).order('name').collect{ |x| [x.name, x.id]}, { :include_blank => "Select a category"} %><br />
  </p>
  <p>
    <%= note.submit 'Save note' %>
  </p>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit your note</h1>
<hr />
<%= render 'notes/form' %>
<hr />
<%= link_to 'Cancel', note_path %>

app/views/notes/index.html.erb
<div class="notesLisDiv" style="text-align: center;">
  <h1 style="margin: 0 auto;">Your notes list: </h1>
</div>
<p><%= link_to "View available categories", categories_path %></p>
<hr />
<ol>
<% @notes.each do |note| %>
  <% if note.user_id === current_user.id %>
    <li><%= link_to note[:title], note %><small> (Updated on: <%= note[:updated_at].strftime("%b %d. %Y") %> - Category: <%= link_to note.category.name, category_path(note.category_id) %>)</small></li>
  <% end %>
<% end %>
</ol>

app/views/notes/new.html.erb
<h1>Add a new note</h1>
<hr />
<%= render 'notes/form' %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/notes/show.html.erb
<% if @note.user_id == current_user.id %>
  <h1 style="margin: 0 auto; text-align: center;"><%= @note[:title] %></h1>
  <nav class="updateNav" style="width: 600px; margin:0 auto; text-align: center;">
    <small>
      <%= @note[:created_at].strftime("%b %d. %Y - %H:%M:%S") %>
      <% if @note[:created_at] != @note[:updated_at] %>
        <small> - updated on: <%= @note[:updated_at].strftime("%b %d. %Y - %H:%M:%S") %></small>
      <% end %>
    </small>
  </nav>
  <table>
    <tr>
      <td>Note Category: </td>
      <td><%= link_to @category[:name],category_path(:id => @note.category_id) %></td>
    </tr>
  </table>

  <small><%= link_to 'Edit note', action: 'edit' %> -
  <%= link_to 'Delete note', @note, :method => :delete, data: { confirm: "Are you sure you want to delete this note?" } %> - <%= link_to 'Categories', categories_path %> - <%= link_to 'Notes', notes_path %></small>
  <hr>
  <% @note[:body].split("\n").each do |line| %>
    <p><%= line %></p>
  <% end %>
<% else %>
  <h3>Please follow one of the below links:</h3>
  <p><%= link_to 'Categories', action: 'index' %> - <%= link_to 'Notes', notes_path %></p>
<% end %>